### ISSUE TITLE
Coveralls does not see mruby.rs for some reason.

### ISSUE THREAD

**Issue by dragostis** [dragostis/mrusty#12]

**Comment by krodyrobi** [comment]
usr/local/include/mruby/array.h
usr/local/include/mruby/value.h

both need to be ignored.

**Comment by dragostis** [comment]
This seems to be related to [this](https://internals.rust-lang.org/t/disabling-gc-sections-when-test-is-specified/2163). There is a merged [PR](https://github.com/rust-lang/rust/pull/31368) on Rust, so nightly builds might do the trick.

`cargo test --release` may also come in handy.

**Comment by dragostis** [comment]
@krodyrobi Seems like `kcov` only finds one of the two test variables generated. (one for `src/tests/` & one for `tests/`)

**Comment by krodyrobi** [comment]
https://github.com/SimonKagstrom/kcov/issues/90
