### ISSUE TITLE
Consider using travis-cargo for travis ci.

### ISSUE THREAD

**Issue by krodyrobi** [dragostis/mrusty#7]
With travis-cargo, you can upload the docs without needing to install anything, so you could use sudo: false in your .travis.yml. This makes use of Travis' container-based build, which is faster.

+ it can build, run tests, bench all in one.

**Comment by dragostis** [comment]
Here's the [link](https://github.com/huonw/travis-cargo).

**Comment by dragostis** [comment]
Should wait for proper docs first.
